/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextileRouteImport } from './routes/textile'
import { Route as SidaiRouteImport } from './routes/sidai'
import { Route as CollectiveRouteImport } from './routes/collective'
import { Route as IndexRouteImport } from './routes/index'

const TextileRoute = TextileRouteImport.update({
  id: '/textile',
  path: '/textile',
  getParentRoute: () => rootRouteImport,
} as any)
const SidaiRoute = SidaiRouteImport.update({
  id: '/sidai',
  path: '/sidai',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectiveRoute = CollectiveRouteImport.update({
  id: '/collective',
  path: '/collective',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collective': typeof CollectiveRoute
  '/sidai': typeof SidaiRoute
  '/textile': typeof TextileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collective': typeof CollectiveRoute
  '/sidai': typeof SidaiRoute
  '/textile': typeof TextileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collective': typeof CollectiveRoute
  '/sidai': typeof SidaiRoute
  '/textile': typeof TextileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collective' | '/sidai' | '/textile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collective' | '/sidai' | '/textile'
  id: '__root__' | '/' | '/collective' | '/sidai' | '/textile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectiveRoute: typeof CollectiveRoute
  SidaiRoute: typeof SidaiRoute
  TextileRoute: typeof TextileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/textile': {
      id: '/textile'
      path: '/textile'
      fullPath: '/textile'
      preLoaderRoute: typeof TextileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidai': {
      id: '/sidai'
      path: '/sidai'
      fullPath: '/sidai'
      preLoaderRoute: typeof SidaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collective': {
      id: '/collective'
      path: '/collective'
      fullPath: '/collective'
      preLoaderRoute: typeof CollectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectiveRoute: CollectiveRoute,
  SidaiRoute: SidaiRoute,
  TextileRoute: TextileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
